controller_list:
  - name: fake_manipulator_controller
    joints:
      - drive0_joint
      - drive1_joint
      - drive2_joint
      - drive3_joint
      - drive4_joint
      - drive5_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home