controller_list:
  - name: fake_arm_controller
    joints:
      - drive0_joint
      - drive1_joint
      - drive2_joint
      - drive3_joint
      - drive4_joint
      - drive5_joint
  - name: fake_gripper_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: home